INSERT INTO policy_sources (name, url, category, description) VALUES
('Anthropic Acceptable Use Policy', 'https://www.anthropic.com/policies/aup', 'AI Platform Policy', 'Anthropic usage restrictions and prohibited activities for Claude AI products and API.'),
('Anthropic Consumer Terms of Service', 'https://www.anthropic.com/policies/consumer-terms', 'AI Platform Policy', 'Terms governing consumer use of Claude including data handling and content ownership.'),
('OpenAI Usage Policies', 'https://openai.com/policies/usage-policies/', 'AI Platform Policy', 'OpenAI prohibited activities and acceptable use guidelines for ChatGPT and GPT API.'),
('OpenAI Service Terms', 'https://openai.com/policies/service-terms/', 'AI Platform Policy', 'OpenAI business and API service terms covering data usage, content ownership, and liability.'),
('Google Generative AI Terms', 'https://policies.google.com/terms/generative-ai', 'AI Platform Policy', 'Google terms and prohibited use policy for Gemini and generative AI services.'),
('Google Gemini API Terms', 'https://ai.google.dev/gemini-api/terms', 'AI Platform Policy', 'Specific terms governing Gemini API usage including rate limits and content restrictions.'),
('Meta Llama Acceptable Use Policy', 'https://www.llama.com/llama4/use-policy/', 'AI Platform Policy', 'Meta prohibited uses and restrictions for Llama open-weight AI models.'),
('Meta Llama Community License', 'https://www.llama.com/llama4/license/', 'AI Platform Policy', 'Meta Llama 4 license terms including commercial use thresholds and redistribution rules.'),
('Microsoft AI Code of Conduct', 'https://learn.microsoft.com/en-us/legal/ai-code-of-conduct', 'AI Platform Policy', 'Microsoft enterprise AI code of conduct for Copilot and Azure AI services.'),
('AWS Bedrock Service Terms', 'https://aws.amazon.com/service-terms/', 'AI Platform Policy', 'Amazon Web Services terms governing Bedrock foundation model access and AI/ML service restrictions.'),
('Apple AI & ML Developer Guidelines', 'https://developer.apple.com/design/human-interface-guidelines/machine-learning', 'AI Platform Policy', 'Apple design and implementation guidelines for machine learning and AI features in apps.'),
('Stability AI Acceptable Use Policy', 'https://stability.ai/use-policy', 'AI Platform Policy', 'Stability AI restrictions on harmful content generation and model misuse.'),
('Midjourney Terms of Service', 'https://docs.midjourney.com/hc/en-us/articles/32083055291277-Terms-of-Service', 'AI Platform Policy', 'Midjourney service agreement covering image generation rights, ownership, and usage restrictions.'),
('Mistral AI Usage Policy', 'https://legal.mistral.ai/terms/usage-policy', 'AI Platform Policy', 'Mistral AI prohibited uses and compliance requirements for open and commercial models.'),
('xAI Grok Acceptable Use Policy', 'https://x.ai/legal/acceptable-use-policy', 'AI Platform Policy', 'xAI restrictions and responsible use guidelines for Grok AI products.'),
('Cohere Usage Policy', 'https://docs.cohere.com/docs/usage-policy', 'AI Platform Policy', 'Cohere prohibited uses and restrictions for enterprise language AI models and API.'),
('Perplexity AI Terms of Service', 'https://www.perplexity.ai/hub/legal/terms-of-service', 'AI Platform Policy', 'Perplexity AI service agreement covering search-augmented AI usage and content policies.'),
('OpenAI Content Policy Hub', 'https://openai.com/policies/', 'AI Platform Policy', 'Central OpenAI policy hub with all governing documents including model spec and safety standards.');